services:
  - type: web
    name: essalud-tregistro
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tregistro-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PANEL_PASSWORD
        sync: false
      - key: RUC_EMPLEADOR
        value: "20131257750"
      - key: NOMBRE_EMPLEADOR
        value: "SEGURO SOCIAL DE SALUD - ESSALUD"
      - key: COD_ESTABLECIMIENTO
        value: "0537"
      - key: SECTOR
        value: "publico"

databases:
  - name: tregistro-db
    plan: free
    databaseName: tregistro
    user: tregistro
